// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network_message.proto

package ch.eiafr.mmmm.net;

public final class NetworkMessage {
  private NetworkMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EventMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 timestamp = 1;
    boolean hasTimestamp();
    long getTimestamp();
    
    // required int32 duration = 2;
    boolean hasDuration();
    int getDuration();
    
    // required string namedEvent = 3;
    boolean hasNamedEvent();
    String getNamedEvent();
    
    // required .ch.eiafr.mmmm.net.EventMessage.Source source = 4;
    boolean hasSource();
    ch.eiafr.mmmm.net.NetworkMessage.EventMessage.Source getSource();
    
    // optional int32 value = 5;
    boolean hasValue();
    int getValue();
  }
  public static final class EventMessage extends
      com.google.protobuf.GeneratedMessage
      implements EventMessageOrBuilder {
    // Use EventMessage.newBuilder() to construct.
    private EventMessage(Builder builder) {
      super(builder);
    }
    private EventMessage(boolean noInit) {}
    
    private static final EventMessage defaultInstance;
    public static EventMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public EventMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.eiafr.mmmm.net.NetworkMessage.internal_static_ch_eiafr_mmmm_net_EventMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.eiafr.mmmm.net.NetworkMessage.internal_static_ch_eiafr_mmmm_net_EventMessage_fieldAccessorTable;
    }
    
    public enum Source
        implements com.google.protobuf.ProtocolMessageEnum {
      KINECT(0, 0),
      WII_HAND(1, 1),
      WII_HEAD(2, 2),
      ;
      
      public static final int KINECT_VALUE = 0;
      public static final int WII_HAND_VALUE = 1;
      public static final int WII_HEAD_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static Source valueOf(int value) {
        switch (value) {
          case 0: return KINECT;
          case 1: return WII_HAND;
          case 2: return WII_HEAD;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Source>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Source>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Source>() {
              public Source findValueByNumber(int number) {
                return Source.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ch.eiafr.mmmm.net.NetworkMessage.EventMessage.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Source[] VALUES = {
        KINECT, WII_HAND, WII_HEAD, 
      };
      
      public static Source valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Source(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:ch.eiafr.mmmm.net.EventMessage.Source)
    }
    
    private int bitField0_;
    // required int64 timestamp = 1;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    // required int32 duration = 2;
    public static final int DURATION_FIELD_NUMBER = 2;
    private int duration_;
    public boolean hasDuration() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getDuration() {
      return duration_;
    }
    
    // required string namedEvent = 3;
    public static final int NAMEDEVENT_FIELD_NUMBER = 3;
    private java.lang.Object namedEvent_;
    public boolean hasNamedEvent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getNamedEvent() {
      java.lang.Object ref = namedEvent_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          namedEvent_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNamedEventBytes() {
      java.lang.Object ref = namedEvent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        namedEvent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .ch.eiafr.mmmm.net.EventMessage.Source source = 4;
    public static final int SOURCE_FIELD_NUMBER = 4;
    private ch.eiafr.mmmm.net.NetworkMessage.EventMessage.Source source_;
    public boolean hasSource() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public ch.eiafr.mmmm.net.NetworkMessage.EventMessage.Source getSource() {
      return source_;
    }
    
    // optional int32 value = 5;
    public static final int VALUE_FIELD_NUMBER = 5;
    private int value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getValue() {
      return value_;
    }
    
    private void initFields() {
      timestamp_ = 0L;
      duration_ = 0;
      namedEvent_ = "";
      source_ = ch.eiafr.mmmm.net.NetworkMessage.EventMessage.Source.KINECT;
      value_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDuration()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNamedEvent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSource()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, duration_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNamedEventBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, source_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, value_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, duration_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNamedEventBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, source_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ch.eiafr.mmmm.net.NetworkMessage.EventMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ch.eiafr.mmmm.net.NetworkMessage.EventMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ch.eiafr.mmmm.net.NetworkMessage.EventMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ch.eiafr.mmmm.net.NetworkMessage.EventMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ch.eiafr.mmmm.net.NetworkMessage.EventMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ch.eiafr.mmmm.net.NetworkMessage.EventMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ch.eiafr.mmmm.net.NetworkMessage.EventMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ch.eiafr.mmmm.net.NetworkMessage.EventMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ch.eiafr.mmmm.net.NetworkMessage.EventMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ch.eiafr.mmmm.net.NetworkMessage.EventMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ch.eiafr.mmmm.net.NetworkMessage.EventMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ch.eiafr.mmmm.net.NetworkMessage.EventMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ch.eiafr.mmmm.net.NetworkMessage.internal_static_ch_eiafr_mmmm_net_EventMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ch.eiafr.mmmm.net.NetworkMessage.internal_static_ch_eiafr_mmmm_net_EventMessage_fieldAccessorTable;
      }
      
      // Construct using ch.eiafr.mmmm.net.NetworkMessage.EventMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        duration_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        namedEvent_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        source_ = ch.eiafr.mmmm.net.NetworkMessage.EventMessage.Source.KINECT;
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.eiafr.mmmm.net.NetworkMessage.EventMessage.getDescriptor();
      }
      
      public ch.eiafr.mmmm.net.NetworkMessage.EventMessage getDefaultInstanceForType() {
        return ch.eiafr.mmmm.net.NetworkMessage.EventMessage.getDefaultInstance();
      }
      
      public ch.eiafr.mmmm.net.NetworkMessage.EventMessage build() {
        ch.eiafr.mmmm.net.NetworkMessage.EventMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ch.eiafr.mmmm.net.NetworkMessage.EventMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ch.eiafr.mmmm.net.NetworkMessage.EventMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ch.eiafr.mmmm.net.NetworkMessage.EventMessage buildPartial() {
        ch.eiafr.mmmm.net.NetworkMessage.EventMessage result = new ch.eiafr.mmmm.net.NetworkMessage.EventMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.duration_ = duration_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.namedEvent_ = namedEvent_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.source_ = source_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.eiafr.mmmm.net.NetworkMessage.EventMessage) {
          return mergeFrom((ch.eiafr.mmmm.net.NetworkMessage.EventMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ch.eiafr.mmmm.net.NetworkMessage.EventMessage other) {
        if (other == ch.eiafr.mmmm.net.NetworkMessage.EventMessage.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasDuration()) {
          setDuration(other.getDuration());
        }
        if (other.hasNamedEvent()) {
          setNamedEvent(other.getNamedEvent());
        }
        if (other.hasSource()) {
          setSource(other.getSource());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasDuration()) {
          
          return false;
        }
        if (!hasNamedEvent()) {
          
          return false;
        }
        if (!hasSource()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              duration_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              namedEvent_ = input.readBytes();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              ch.eiafr.mmmm.net.NetworkMessage.EventMessage.Source value = ch.eiafr.mmmm.net.NetworkMessage.EventMessage.Source.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                source_ = value;
              }
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              value_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 timestamp = 1;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // required int32 duration = 2;
      private int duration_ ;
      public boolean hasDuration() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getDuration() {
        return duration_;
      }
      public Builder setDuration(int value) {
        bitField0_ |= 0x00000002;
        duration_ = value;
        onChanged();
        return this;
      }
      public Builder clearDuration() {
        bitField0_ = (bitField0_ & ~0x00000002);
        duration_ = 0;
        onChanged();
        return this;
      }
      
      // required string namedEvent = 3;
      private java.lang.Object namedEvent_ = "";
      public boolean hasNamedEvent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getNamedEvent() {
        java.lang.Object ref = namedEvent_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          namedEvent_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNamedEvent(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        namedEvent_ = value;
        onChanged();
        return this;
      }
      public Builder clearNamedEvent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        namedEvent_ = getDefaultInstance().getNamedEvent();
        onChanged();
        return this;
      }
      void setNamedEvent(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        namedEvent_ = value;
        onChanged();
      }
      
      // required .ch.eiafr.mmmm.net.EventMessage.Source source = 4;
      private ch.eiafr.mmmm.net.NetworkMessage.EventMessage.Source source_ = ch.eiafr.mmmm.net.NetworkMessage.EventMessage.Source.KINECT;
      public boolean hasSource() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public ch.eiafr.mmmm.net.NetworkMessage.EventMessage.Source getSource() {
        return source_;
      }
      public Builder setSource(ch.eiafr.mmmm.net.NetworkMessage.EventMessage.Source value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        source_ = value;
        onChanged();
        return this;
      }
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000008);
        source_ = ch.eiafr.mmmm.net.NetworkMessage.EventMessage.Source.KINECT;
        onChanged();
        return this;
      }
      
      // optional int32 value = 5;
      private int value_ ;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getValue() {
        return value_;
      }
      public Builder setValue(int value) {
        bitField0_ |= 0x00000010;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        value_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ch.eiafr.mmmm.net.EventMessage)
    }
    
    static {
      defaultInstance = new EventMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ch.eiafr.mmmm.net.EventMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ch_eiafr_mmmm_net_EventMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ch_eiafr_mmmm_net_EventMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025network_message.proto\022\021ch.eiafr.mmmm.n" +
      "et\"\300\001\n\014EventMessage\022\021\n\ttimestamp\030\001 \002(\003\022\020" +
      "\n\010duration\030\002 \002(\005\022\022\n\nnamedEvent\030\003 \002(\t\0226\n\006" +
      "source\030\004 \002(\0162&.ch.eiafr.mmmm.net.EventMe" +
      "ssage.Source\022\r\n\005value\030\005 \001(\005\"0\n\006Source\022\n\n" +
      "\006KINECT\020\000\022\014\n\010WII_HAND\020\001\022\014\n\010WII_HEAD\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ch_eiafr_mmmm_net_EventMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ch_eiafr_mmmm_net_EventMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ch_eiafr_mmmm_net_EventMessage_descriptor,
              new java.lang.String[] { "Timestamp", "Duration", "NamedEvent", "Source", "Value", },
              ch.eiafr.mmmm.net.NetworkMessage.EventMessage.class,
              ch.eiafr.mmmm.net.NetworkMessage.EventMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
